import Head from "next/head";
import Image from "next/image";
import Navbar from "./components/navbar";
import Main from "./components/main";
import About from "./components/About";
import Skills from "./components/Skill";
import Project from "./components/Project";
import Contact from "./components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Aga's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Project />
      <Contact />
    </div>
  );
}
